spring:
  jackson:
    date-format: "yyyy-MM-dd"
    time-zone: "GMT+08"
  mvc:
    view:
      suffix: .jsp
      prefix:  /
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz?useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
server:
  jsp-servlet:
    init-parameters:
      development: true
  port: 8888

mybatis:
  mapper-locations: classpath:com/wcf/mapper/*.xml


# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
  - 192.168.29.133:22122